/*Aviso de Privacidade: Todos os dados, IDs, nomes de tabelas e variáveis originais foram anonimizados
 e descaracterizados para proteger a infraestrutura e as informações sensíveis da base original, mantendo
  apenas a lógica estrutural para fins de demonstração.*/
SELECT DISTINCT
    FERRAMENTA.COD_FERRAMENTA AS ID_Ferramenta
    , FERRAMENTA.COD_MATERIAL AS ID_Material
    , MATERIAL.DESCRICAO DESC_MATERIAL
    , CASE 
        WHEN FC.DATA_DEVOLUCAO IS NULL THEN 'EM USO'
        ELSE 'DEVOLVIDA'
    END AS SITUACAO
    , FC.PERMANENTE 
    , TO_CHAR(FERRAMENTA.DATAINICIO, 'DD/MM/YYYY') AS DATA_inicio
    , FERRAMENTA.COD_ALMOXARIFADO AS ID_almoxarifado
    , ALMOXARIFADO.DESCRICAOALMOXARIFADO AS Almoxarifado
    , FERRAMENTA.ID_MARCA AS ID_Marca
    , FERRAMENTA_MARCA.DESCRICAO_MARCA AS Marca
    , FERRAMENTA.ID_FERRAMENTA_MODELO AS ID_Modelo
    , FERRAMENTA_MODELO.DESCRICAO_MODELO AS Modelo
    , FERRAMENTA.ID_TIPO
    , FERRAMENTA_TIPO.DESCRICAO_TIPO
    , TO_CHAR(FC.DATA_ENTREGA, 'DD/MM/YYYY') AS DATA_entrega
    , TO_CHAR(FC.DATA_PREVISTA_DEVOLUCAO, 'DD/MM/YYYY') AS DATA_prevista_devolucao
    , TO_CHAR(FC.DATA_DEVOLUCAO, 'DD/MM/YYYY') AS DATA_devolucao
    , FC.COD_FUNCIONARIO AS Id_Portador
    ,CASE 
        WHEN INSTR(RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO), ' ') > 0 THEN 
            SUBSTR(RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO), 1, INSTR(RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO), ' ') + 1) || '.'
        ELSE 
            RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO)
    END AS PORTADOR
    ,COALESCE(RH."FN_DEPARTAMENTO" (1
                           ,FC.COD_FUNCIONARIO  
                           ,RH."FN_BUSCA_PERIODO_TRAB" (1
                                                   ,FC.COD_FUNCIONARIO
                                                   ,sysdate)
                           ,sysdate
                           ,'D'), 'Não informado') AS SETOR
    , FC.COD_Funcionario_ENTREGA AS ID_Emissor
    , COALESCE(CASE 

        WHEN INSTR( RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO_ENTREGA), ' ') > 0 THEN 
            SUBSTR( RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO_ENTREGA), 1, INSTR( RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO_ENTREGA), ' ') + 1) || '.'
        ELSE 
             RH."FN_NOMEFUNCIONARIO"(1, FC.COD_FUNCIONARIO_ENTREGA) 
    END, 'Não informado') AS Emissor
    , coalesce(FC.OBSERVACAO,'sem observação' ) AS Observacao
    , MATERIAL.COD_UNIDADE AS ID_Unidade
FROM
    MATERIAL.FERRAMENTA FERRAMENTA
    ,MATERIAL.FERRAMENTA_CONTROLE FC
    ,MATERIAL.MATERIAL
    ,MATERIAL.ALMOXARIFADO ALMOXARIFADO
    ,MATERIAL.FERRAMENTA_MARCA FERRAMENTA_MARCA
    ,MATERIAL.FERRAMENTA_MODELO FERRAMENTA_MODELO
    ,MATERIAL.FERRAMENTA_TIPO FERRAMENTA_TIPO
WHERE  0 = 0
    AND FC.ID_FERRAMENTA = FERRAMENTA.SEQUENCIA
    AND FC.DATA_ENTREGA = (
        SELECT MAX(FC2.DATA_ENTREGA)
        FROM MATERIAL.FERRAMENTA_CONTROLE FC2
        WHERE FC2.ID_FERRAMENTA = FERRAMENTA.SEQUENCIA
    )
    AND FERRAMENTA.DATATERMINO IS NULL
    AND FERRAMENTA.COD_FERRAMENTA IS NOT NULL
    AND FERRAMENTA.COD_MATERIAL IS NOT NULL
    AND FERRAMENTA.COD_GRUPOEMPRESA = 1
    AND FERRAMENTA.COD_EMPRESA = 1
    AND FERRAMENTA.COD_FILIAL = 1
    AND FERRAMENTA.COD_MATERIAL = MATERIAL.COD_MATERIAL
    AND ALMOXARIFADO.COD_ALMOXARIFADO (+)= FERRAMENTA.COD_ALMOXARIFADO 
    AND ALMOXARIFADO.COD_GRUPOEMPRESA (+)= FERRAMENTA.COD_GRUPOEMPRESA 
    AND ALMOXARIFADO.COD_EMPRESA (+)= FERRAMENTA.COD_EMPRESA      
    AND ALMOXARIFADO.COD_FILIAL (+)= FERRAMENTA.COD_FILIAL       
    AND FERRAMENTA_MARCA.ID_MARCA (+)= FERRAMENTA.ID_MARCA
    AND FERRAMENTA_MODELO.ID_FERRAMENTA_MODELO (+)= FERRAMENTA.ID_FERRAMENTA_MODELO
    AND FERRAMENTA_TIPO.ID_TIPO (+)= FERRAMENTA.ID_TIPO
    
ORDER BY FERRAMENTA.COD_FERRAMENTA DESC